version: '3'
services:
  playliststore:
    image: mongo
    ports:
      - "27017:27017"
    command: "--smallfiles"  

  data:
    build:
      context: .
    volumes:
      - soundshare:/tmp/sharesound

  mopidy:
    build:
      context: .
      dockerfile: DockerfileMopidy
    expose:
      - 6600
      - 6680
    ports:
      - "6600:6600"
      - "6680:6680"
#    environment:
#      - GST_DEBUG=3
    depends_on:
      - snapserver
      - data
    volumes:
      - ./mopidy-master.conf:/var/lib/mopidy/.config/mopidy/mopidy.conf:ro
      - soundshare:/tmp/sharesound
    network_mode: "host"

  snapserver:
    image: nolte/snapcast-server
    depends_on:
      - data
    volumes:
      - soundshare:/tmp/sharesound
    command: "-s pipe:///tmp/sharesound/snapfifo?name=Radio"

  snapclient:
    image: nolte/snapcast-client
    links:
     - snapserver:snapserverhost
    depends_on:
      - snapserver
    devices:
     - "/dev/snd/:/dev/snd/"
    command: "-h snapserverhost"

  upmpdcli:
    image: nolte/upmpdcli:development
    depends_on:
      - mopidy
    command: "-h localhost -p 6600 -f mopidy"
    network_mode: "host"


volumes:
  soundshare:
